version: "3.2"
services:
  db:
    image: "postgres:11.1-alpine"
    container_name: learn-clojure-db
    command: postgres  -c shared_buffers=256MB -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=clojurefriends
    tmpfs:
      - /var/lib/postgresql/data-clojurefriends
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
